FROM mcr.microsoft.com/devcontainers/base:ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  autoconf \
  build-essential \
  libdb-dev \
  libffi-dev \
  libgdbm-dev \
  libgdbm6 \
  libgmp-dev \
  libncurses5-dev \
  libreadline6-dev \
  libsqlite3-dev \
  libssl-dev \
  libyaml-dev \
  openjdk-11-jdk \
  patch \
  postgresql-client \
  rustc \
  sqlite3 \
  shellcheck \
  uuid-dev \
  zlib1g-dev
