import { PageModel } from '@stackbit/types';

export const CaseStudy: PageModel = {
  type: 'page',
  name: 'CaseStudy',
  label: 'Page',
  urlPath: '/work/{slug}',
  filePath: 'content/pages/work/{slug}.md',
  hideContent: true,
  thumbnail: 'https://assets.stackbit.com/components/models/thumbnails/default.png',
  fields: [
    {
      type: 'string',
      name: 'slug',
      label: 'Slug',
      description: 'A unique url for this page starting with "/"',
      required: true,
    },
    {
      type: 'string',
      name: 'title',
      label: 'Title',
      default: 'This Is a New Page',
      required: true,
    },
    {
      type: 'string',
      name: 'description',
      label: 'Description',
      default: 'A brief (1-3 sentence) summary of the content',
      required: true,
    },
    {
      type: 'date',
      name: 'date',
      label: 'The publication date',
      required: true,
    },
    {
      type: 'string',
      name: 'client',
      label: 'Client name',
      default: 'Acme',
      required: true,
    },
    {
      type: 'list',
      name: 'summary',
      label: 'Summary',
      description: 'A list of paragraphs used for the summary',
      required: true,
      items: { type: 'text' },
    },
    {
      type: 'image',
      name: 'logo',
      label: 'Client logo',
      default: '/images/default.png',
      required: true,
    },
    {
      type: 'model',
      name: 'image',
      label: 'Image',
      models: ['Image'],
      required: true,
    },
    {
      type: 'list',
      name: 'services',
      label: 'Service tags',
      description: 'A list of services used in this case study',
      required: true,
      items: { type: 'text' },
    },
    {
      type: 'model',
      name: 'testimonial',
      label: 'Testimonial',
      models: ['Testimonial'],
      required: true,
    },
  ],
};
