import { DataModel } from '@stackbit/types';

export const ThemeStyle: DataModel = {
  type: 'data',
  name: 'ThemeStyle',
  label: 'Theme Style',
  labelField: 'fontHeadlines',
  fields: [
    {
      type: 'object',
      name: 'colors',
      label: 'Color palette',
      required: true,
      hidden: false,
      localized: false,
      group: 'color-palettes',
      readOnly: true,
      fields: [
        {
          type: 'string',
          name: 'black',
          required: true,
          default: '#0a0a0a',
        },
        {
          type: 'string',
          name: 'white',
          required: true,
          default: '#0a0a0a',
        },
        {
          type: 'model',
          name: 'neutral',
          required: true,
          models: ['ColorPalette'],
          default: {
            type: 'ColorPalette',
            '100': '#f5f5f5',
            '200': '#e5e5e5',
            '300': '#d4d4d4',
            '400': '#a3a3a3',
            '500': '#737373',
            '600': '#525252',
            '700': '#404040',
            '800': '#262626',
            '900': '#171717',
          },
        },
        {
          type: 'model',
          name: 'primary',
          required: true,
          models: ['ColorPalette'],
          default: {
            type: 'ColorPalette',
            '100': '#cffafe',
            '200': '#a5f3fc',
            '300': '#67e8f9',
            '400': '#22d3ee',
            '500': '#06b6d4',
            '600': '#0891b2',
            '700': '#0e7490',
            '800': '#155e75',
            '900': '#164e63',
          },
        },
        {
          type: 'model',
          name: 'secondary',
          required: true,
          models: ['ColorPalette'],
          default: {
            type: 'ColorPalette',
            '100': '#e0e7ff',
            '200': '#c7d2fe',
            '300': '#a5b4fc',
            '400': '#818cf8',
            '500': '#6366f1',
            '600': '#4f46e5',
            '700': '#4338ca',
            '800': '#3730a3',
            '900': '#312e81',
          },
        },
        {
          type: 'model',
          name: 'accent',
          required: true,
          models: ['ColorPalette'],
          default: {
            type: 'ColorPalette',
            '100': '#ccfbf1',
            '200': '#99f6e4',
            '300': '#5eead4',
            '400': '#2dd4bf',
            '500': '#14b8a6',
            '600': '#0d9488',
            '700': '#0f766e',
            '800': '#115e59',
            '900': '#134e4a',
          },
        },
        {
          type: 'model',
          name: 'info',
          required: true,
          models: ['ColorPalette'],
          default: {
            type: 'ColorPalette',
            '100': '#dbeafe',
            '200': '#bfdbfe',
            '300': '#93c5fd',
            '400': '#60a5fa',
            '500': '#3b82f6',
            '600': '#2563eb',
            '700': '#1d4ed8',
            '800': '#1e40af',
            '900': '#1e3a8a',
          },
        },
        {
          type: 'model',
          name: 'success',
          required: true,
          models: ['ColorPalette'],
          default: {
            type: 'ColorPalette',
            '100': '#d1fae5',
            '200': '#a7f3d0',
            '300': '#6ee7b7',
            '400': '#34d399',
            '500': '#10b981',
            '600': '#059669',
            '700': '#047857',
            '800': '#065f46',
            '900': '#064e3b',
          },
        },
        {
          type: 'model',
          name: 'warning',
          required: true,
          models: ['ColorPalette'],
          default: {
            type: 'ColorPalette',
            '100': '#fef3c7',
            '200': '#fde68a',
            '300': '#fcd34d',
            '400': '#fbbf24',
            '500': '#f59e0b',
            '600': '#d97706',
            '700': '#b45309',
            '800': '#92400e',
            '900': '#78350f',
          },
        },
        {
          type: 'model',
          name: 'danger',
          required: true,
          models: ['ColorPalette'],
          default: {
            type: 'ColorPalette',
            '100': '#ffe4e6',
            '200': '#fecdd3',
            '300': '#fda4af',
            '400': '#fb7185',
            '500': '#f43f5e',
            '600': '#e11d48',
            '700': '#be123c',
            '800': '#9f1239',
            '900': '#881337',
          },
        },
      ],
    },
    {
      type: 'enum',
      name: 'fontBody',
      label: 'Font - body & captions',
      required: false,
      default: 'sans',
      hidden: false,
      localized: false,
      options: [
        {
          label: 'Sans',
          value: 'sans',
        },
        {
          label: 'Serif',
          value: 'serif',
        },
      ],
      group: 'text-styles',
    },
    {
      type: 'enum',
      name: 'fontHeadlines',
      label: 'Font - headlines & subtitles',
      required: false,
      default: 'sans',
      hidden: false,
      localized: false,
      options: [
        {
          label: 'Sans',
          value: 'sans',
        },
        {
          label: 'Serif',
          value: 'serif',
        },
      ],
      group: 'text-styles',
    },
    {
      type: 'model',
      name: 'h1',
      label: 'H1',
      required: false,
      hidden: false,
      localized: false,
      models: ['ThemeStyleHeading'],
      group: 'text-styles',
      readOnly: true,
    },
    {
      type: 'model',
      name: 'h2',
      label: 'H2',
      required: false,
      hidden: false,
      localized: false,
      models: ['ThemeStyleHeading'],
      group: 'text-styles',
      readOnly: true,
    },
    {
      type: 'model',
      name: 'h3',
      label: 'H3',
      required: false,
      hidden: false,
      localized: false,
      models: ['ThemeStyleHeading'],
      group: 'text-styles',
      readOnly: true,
    },
    {
      type: 'model',
      name: 'h4',
      label: 'H4',
      required: false,
      hidden: false,
      localized: false,
      models: ['ThemeStyleHeading'],
      group: 'text-styles',
      readOnly: true,
    },
    {
      type: 'model',
      name: 'h5',
      label: 'H5',
      required: false,
      hidden: false,
      localized: false,
      models: ['ThemeStyleHeading'],
      group: 'text-styles',
      readOnly: true,
    },
    {
      type: 'model',
      name: 'h6',
      label: 'H6',
      required: false,
      hidden: false,
      localized: false,
      models: ['ThemeStyleHeading'],
      group: 'text-styles',
      readOnly: true,
    },
    {
      type: 'model',
      name: 'buttonPrimary',
      label: 'Primary button',
      required: false,
      hidden: false,
      localized: false,
      models: ['ThemeStyleButton'],
      group: 'button-styles',
      readOnly: true,
    },
    {
      type: 'model',
      name: 'buttonSecondary',
      label: 'Secondary button',
      required: false,
      hidden: false,
      localized: false,
      models: ['ThemeStyleButton'],
      group: 'button-styles',
      readOnly: true,
    },
    {
      type: 'model',
      name: 'linkPrimary',
      label: 'Primary link',
      required: false,
      hidden: false,
      localized: false,
      models: ['ThemeStyleLink'],
      group: 'button-styles',
      readOnly: true,
    },
    {
      type: 'model',
      name: 'linkSecondary',
      label: 'Secondary link',
      required: false,
      hidden: false,
      localized: false,
      models: ['ThemeStyleLink'],
      group: 'button-styles',
      readOnly: true,
    },
  ],
  fieldGroups: [
    {
      name: 'color-palettes',
      label: 'Colors',
      icon: 'fill-drip',
    },
    {
      name: 'text-styles',
      label: 'Text',
      icon: 'text',
    },
    {
      name: 'button-styles',
      label: 'Buttons',
      icon: 'palette',
    },
  ],
  singleInstance: true,
  file: 'style.json',
};
